name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types: [ published ]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: pwd
          POSTGRES_DB: deno
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5000:5432

    steps:
      - name: Clone repo
        uses: actions/checkout@master
      - name: Install deno
        uses: denolib/setup-deno@master
        with: 
          deno-version: 1.0.2
      - name: Check formatting
        run: deno fmt --check
      - name: Run tests
        run: deno test
